### ISSUE TITLE
_find doesn't work

### ISSUE THREAD

**Issue by kpietraszek** [1999/node-couchdb#22]
after last update v1.1.1 

 database.insert(dbName + '/_find', { selector: {}}).then(({data, headers, status}) => {
          console.log('succes');
        }, err => {
          console.error(err);
        });

 returns Error: Unexpected status code while inserting document into the database: 200 
and never returns 'success' in this case

**Comment by pvomhoff** [comment]
This library is currently not optimized for v2 of CouchDB so the `find()` method is not implemented yet.
The `insert` function is for inserting documents not to find them :)

I just took a look into the code and implemented a draft for the `find` function.
But the tests are failing because some of the functions are couchDB v1.

I dont know how much work it will be to also implement v2.

@1999 Do you have any to implement v2 of CouchDb?

**Comment by kpietraszek** [comment]
Thank you for your answer. 
I know that insert was design for inserting things but it works exactly like post so I used it for find as well.
For all people having same problem just downgrade node-couchdb to 1.1.0 and find will work perfectly.

**Comment by 1999** [comment]
Sure. If you point me to the docs about _find, I will try to implement it asap @kpietraszek

**Comment by Flamenco** [comment]
http://docs.couchdb.org/en/2.0.0/api/database/find.html

This is the mango search I issued a PR for.

**Comment by 1999** [comment]
Aha. Could you please look into #20? Does it it your needs?

**Comment by a-gundy** [comment]
When will this feature be added to a new release of node-couchdb?

**Comment by 1999** [comment]
@a-gundy can you use "mango" method of node-couchdb for this?

**Comment by pvomhoff** [comment]
@1999 I had the problem that the version with `mango` is not published on npm yet.
I had to the use the github link directly.

Maybe @a-gundy discovered the same.

Can you publish it? :)

**Comment by 1999** [comment]
@pvomhoff sorry, I completely forgot about this. Done 1.2.0
