### ISSUE TITLE
Precompiled Publish

### ISSUE THREAD

**Issue by a-gundy** [1999/node-couchdb#29]
I'm trying to use node-couchdb in a ReactJS app that is based on the Create React App template. Unfortunately, the scripts to compile the app won't work because of this library. Apparently the package needs to be pre-compiled in this case. 

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Any chance you could publish the project pre-compiled? 

Thanks

![create-app-help](https://user-images.githubusercontent.com/9537391/30759564-56fe883e-9f9c-11e7-8da2-5e59125d9598.png)

**Comment by 1999** [comment]
I'm not sure if this will help here. Currently node-couchdb published version is [compiled](https://unpkg.com/node-couchdb@1.2.0/dist/es2015.js) already. Maybe the problem is that it's using node-specific APIs. Could you please show the actual error that you see during react build?

**Comment by a-gundy** [comment]
![error](https://user-images.githubusercontent.com/9537391/30867587-03ca81d2-a2a2-11e7-8432-dc353f331b91.jpg)

**Comment by 1999** [comment]
That's kinda interesting. I tried to install `create-react-app` and look into its code. It appears that the error you see is actually not the error of either `node-couchdb` or `create-react-app`. This is UglifyJS error because it [can't process ES6 code](https://github.com/webpack/webpack/issues/2972). The execution chain is like this:

1. you run `yarn build`
2. it executes `react-scripts build`
3. `react-scripts` spawns node process which executes its scripts/build.js file
4. inside this file webpack compiler process is spawned
5. inside webpack compiler UglifyJS is being used and it's failing.

So you can go with two different ways:
1. You can import from ES5 build: `import NodeCouchDb from 'node-couchdb/dist/legacy'`
2. You can try to configure your [own babel config](https://github.com/webpack/webpack/issues/2972#issuecomment-277392316) within your React app. However it looks like `create-react-app` [warns you](https://github.com/facebookincubator/create-react-app#converting-to-a-custom-setup) against this.

Hopefully this was helpful.
